build: update to Micronaut 4
micronaut-projects/micronaut-redis pull request #331
Opened 2022-11-28 06:20 UTC by sdelamo

2022-11-28 06:23 UTC, sdelamo commented
@timyates could you look into this?

2022-12-01 14:09 UTC, timyates commented
Still failing, I suspect it's an issue in core

2022-12-15 16:01 UTC, timyates commented
@sdelamo Fixed.

I had to pass the ConversionService in to the RedisSessionStore, which meant I had to change the public constructor

After a discussion in the meeting, there was no preference to simply making the change over deprecating the old constructor, so I went with the former and added it to the accepted-api-changes

2022-12-15 16:30 UTC, wetted requested changes

2022-12-15 16:30 UTC, wetted commented on gradle.properties
> +micronautVersion=4.0.0-SNAPSHOT
I started moving all these version properties to libs.versions.toml, e.g.
```
micronaut-docs = "2.0.0"
micronaut = "4.0.0-SNAPSHOT"
micronaut-test = "4.0.0-SNAPSHOT"
groovy = "4.0.6"
spock = "2.2-groovy-4.0"
```

2022-12-15 16:30 UTC, wetted commented on gradle/libs.versions.toml
>  projectreactor = { module = 'io.projectreactor:reactor-core' }
I think this can be eliminated in favor of `mn.reactor`

2022-12-15 16:30 UTC, wetted commented on redis-lettuce/build.gradle
>      testImplementation libs.projectreactor
I think this can now be `mn.reactor`

2022-12-15 16:41 UTC, wetted approved these changes

2022-12-20 09:51 UTC, merged