MasterReplica and ReadFrom Support
micronaut-projects/micronaut-redis pull request #544
Opened 2024-07-02 14:19 UTC by Mike-Svendsen-IL

This PR adds support for using a MasterReplica connection by providing the `redis.replica-uris` setting in combination with the `redis.uri` setting.

It adds support for configuring the Redis ReadFrom settings for MasterReplica and Cluster connections through the `redis.read-from` setting, allowing users to configure how they would like to spread reads across their redis instances.

This implements the enhancement requested in https://github.com/micronaut-projects/micronaut-redis/issues/430

2024-07-02 14:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-redis?pullRequest=544) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-redis?pullRequest=544) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-redis?pullRequest=544) it.</sub>

2024-07-03 04:52 UTC, graemerocher requested changes

2024-07-03 04:52 UTC, graemerocher commented on redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/AbstractRedisConfiguration.java
> +    public List<RedisURI> getReplicaUris() {
could you add `@since 6.5.0` to all new pubic methods.

2024-07-03 04:52 UTC, graemerocher commented on redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/AbstractRedisConfiguration.java
> +    public List<RedisURI> getReplicaUris() {
please declare nullability annotations on all new methods and arguments (Micronaut's `Nullable` and `@NonNull`. If anything can be `null` consider returning `Optional`

2024-07-03 04:52 UTC, graemerocher commented on redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/DefaultRedisClientFactory.java
> +    @Singleton
remove `@Bean` and `@Singleton` if this is deprecated

2024-07-03 04:52 UTC, graemerocher commented on redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/DefaultRedisClusterClientFactory.java
> +    @Singleton
remove `@Bean` and `@Singleton` if this is deprecated

2024-07-03 04:52 UTC, graemerocher commented on redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/NamedRedisClientFactory.java
> +            if (connection instanceof StatefulRedisClusterConnection && config.getReadFrom() != null) {
use `connection instanceof StatefulRedisClusterConnection<?, ?> conn` to avoid the cast

2024-07-03 04:52 UTC, graemerocher commented on redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/NamedRedisClientFactory.java
> +                ((StatefulRedisMasterReplicaConnection<K, V>) connection).setReadFrom(config.getReadFrom());
this seems to need an instanceof check

2024-07-03 15:00 UTC, graemerocher approved these changes

2024-07-03 15:02 UTC, Mike-Svendsen-IL commented on redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/NamedRedisClientFactory.java
> +                ((StatefulRedisMasterReplicaConnection<K, V>) connection).setReadFrom(config.getReadFrom());
The connection is created immediately above, so the compiler knows the cast is ok.

2024-07-04 13:03 UTC, merged

2024-07-04 13:03 UTC, graemerocher commented
Thanks for the contribution!